export const GET_DISCUSSION_DETAILS = 'GET_DISCUSSION_DETAILS';
export const LOGOUT_DISCUSSION = 'LOGOUT_DISCUSSION';
export const PARTICIPANTS_ADDED = 'PARTICIPANTS_ADDED';
export const PARTICIPANTS_LEFT = 'PARTICIPANTS_LEFT';
export const UPDATE_PARTICIPANT_SETTINGS = 'UPDATE_PARTICIPANT_SETTINGS';
export const SET_MICROPHONE_STREAM = 'SET_MICROPHONE_STREAM';
export const SET_SCREEN_SHARING_STREAM = 'SET_SCREEN_SHARING_STREAM';
export const SET_VIDEO_STREAM = 'SET_VIDEO_STREAM';
